site_name: pymeineta Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api_reference.md
  - FAQ: faq.md
repo_url: https://github.com/lechtob/pymeineta
repo_name: GitHub
edit_uri: edit/main/docs/
